"""
core/code_executor.py — Sandbox code executor for AI-generated Python code.

Executes user-provided Python code (generated by Gemini AI) in a restricted
namespace with blocked dangerous imports and a 30-second timeout.
"""

import contextlib
import io
import threading
import time
import traceback
from typing import Any, Literal, Optional

import matplotlib
matplotlib.use("Agg")  # Use non-interactive backend for sandbox execution
import matplotlib.figure
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import plotly.graph_objs
import seaborn as sns

from typing import TypedDict


# ---------------------------------------------------------------------------
# Task 6.1 — ExecutionResult TypedDict
# ---------------------------------------------------------------------------

class ExecutionResult(TypedDict):
    """Result returned by the code executor after running user-provided code.

    Fields
    ------
    output_type : Literal["dataframe", "figure", "text", "error"]
        Category of the primary output produced by the executed code.
    data : Any
        The actual output value:
        - ``pd.DataFrame`` when output_type is "dataframe"
        - ``matplotlib.figure.Figure`` or ``plotly.graph_objs.Figure`` when "figure"
        - ``str`` when "text" or "error"
    stdout : str
        Everything written to stdout via ``print()`` during execution.
    error : Optional[str]
        Full traceback string if an exception occurred, otherwise ``None``.
    execution_time_ms : float
        Wall-clock execution time in milliseconds.
    """

    output_type: Literal["dataframe", "figure", "text", "error"]
    data: Any
    stdout: str
    error: Optional[str]
    execution_time_ms: float


# ---------------------------------------------------------------------------
# Task 6.2 — Blocked modules and sandbox helpers
# ---------------------------------------------------------------------------

#: Modules that must never be importable inside the sandbox.
_BLOCKED_MODULES: frozenset[str] = frozenset(
    {"os", "sys", "subprocess", "shutil", "socket"}
)

#: Execution timeout in seconds.
_TIMEOUT_SECONDS: int = 90


def _make_restricted_import(original_import):
    """Return a replacement ``__import__`` that blocks dangerous modules.

    Parameters
    ----------
    original_import : callable
        The built-in ``__import__`` function to delegate safe imports to.

    Returns
    -------
    callable
        A wrapper that raises ``ImportError`` for blocked module names.
    """

    def _restricted_import(name, *args, **kwargs):
        # Block the top-level module name (e.g. "os.path" → "os")
        top_level = name.split(".")[0]
        if top_level in _BLOCKED_MODULES:
            raise ImportError(
                f"Import modul '{name}' diblokir demi keamanan sandbox."
            )
        return original_import(name, *args, **kwargs)

    return _restricted_import


def _build_namespace(df: pd.DataFrame) -> dict:
    """Build the restricted execution namespace for the sandbox.

    The namespace pre-populates common data-science libraries and a *copy*
    of the active DataFrame so that user code cannot mutate the original.

    Parameters
    ----------
    df : pd.DataFrame
        The active DataFrame to expose inside the sandbox.

    Returns
    -------
    dict
        Namespace dictionary ready to be passed to ``exec()``.
    """
    df_copy = df.copy()

    # Build a restricted builtins dict that intercepts __import__
    import builtins as _builtins_module

    restricted_builtins = dict(vars(_builtins_module))
    restricted_builtins["__import__"] = _make_restricted_import(
        _builtins_module.__import__
    )

    namespace: dict = {
        "__builtins__": restricted_builtins,
        # Pre-imported libraries available to user code
        "pd": pd,
        "np": np,
        "plt": plt,
        "px": px,
        "go": go,
        "sns": sns,
        # Active DataFrame (copy so original is never mutated)
        "df": df_copy,
    }

    # Ensure matplotlib is in non-interactive mode and no stale figures
    # are left open from previous executions — both can cause hangs.
    plt.ioff()
    plt.close("all")

    return namespace


# ---------------------------------------------------------------------------
# Task 6.3 — Output detection
# ---------------------------------------------------------------------------

def _detect_output(
    namespace: dict,
    original_df: pd.DataFrame,
    captured_stdout: str,
) -> ExecutionResult:
    """Inspect the sandbox namespace after execution and classify the output.

    Detection priority:
    1. ``fig`` variable present (Matplotlib or Plotly) → ``output_type="figure"``
    2. ``df`` variable changed → ``output_type="dataframe"``
    3. Non-empty captured stdout → ``output_type="text"``
    4. Default → ``output_type="text"`` with a localised no-output message.

    Parameters
    ----------
    namespace : dict
        The sandbox namespace after ``exec()`` has run.
    original_df : pd.DataFrame
        The original DataFrame passed to ``execute()`` (before execution).
    captured_stdout : str
        Everything written to stdout during execution.

    Returns
    -------
    ExecutionResult
        Populated result with ``stdout`` and ``error=None``.
    """
    # --- Priority 1: Figure variable (checked FIRST — takes precedence over df changes) ---
    if "fig" in namespace:
        fig = namespace["fig"]
        if isinstance(
            fig,
            (matplotlib.figure.Figure, plotly.graph_objs.Figure),
        ):
            return ExecutionResult(
                output_type="figure",
                data=fig,
                stdout=captured_stdout,
                error=None,
                execution_time_ms=0.0,
            )

    # --- Priority 2: DataFrame changed ---
    if "df" in namespace and isinstance(namespace["df"], pd.DataFrame):
        try:
            changed = not namespace["df"].equals(original_df)
        except Exception:
            # If comparison itself fails (e.g. mixed types), treat as changed
            changed = True

        if changed:
            return ExecutionResult(
                output_type="dataframe",
                data=namespace["df"],
                stdout=captured_stdout,
                error=None,
                execution_time_ms=0.0,  # caller fills this in
            )

    # --- Priority 3: Captured stdout ---
    if captured_stdout.strip():
        return ExecutionResult(
            output_type="text",
            data=captured_stdout,
            stdout=captured_stdout,
            error=None,
            execution_time_ms=0.0,
        )

    # --- Default: no meaningful output ---
    return ExecutionResult(
        output_type="text",
        data="(Kode dieksekusi tanpa output)",
        stdout=captured_stdout,
        error=None,
        execution_time_ms=0.0,
    )


# ---------------------------------------------------------------------------
# Task 6.4 — Main execute() function
# ---------------------------------------------------------------------------

def execute(code: str, df: pd.DataFrame) -> ExecutionResult:
    """Execute AI-generated Python code in a restricted sandbox.

    The function:
    - Runs ``code`` inside a namespace that exposes ``pd``, ``np``, ``plt``,
      ``px``, ``go``, and a copy of ``df``.
    - Blocks imports of dangerous modules (``os``, ``sys``, ``subprocess``,
      ``shutil``, ``socket``).
    - Enforces a 30-second wall-clock timeout via ``threading.Timer``.
    - Captures all ``print()`` output via ``io.StringIO``.
    - **Never raises an exception to the caller** — all errors are returned
      as ``ExecutionResult(output_type="error", ...)``.

    Parameters
    ----------
    code : str
        Python source code to execute.
    df : pd.DataFrame
        The active DataFrame; a copy is placed in the sandbox as ``df``.

    Returns
    -------
    ExecutionResult
        Always returns a valid ``ExecutionResult``; never raises.
    """
    start_time = time.perf_counter()

    # Keep a snapshot of the original DataFrame for change detection
    original_df = df.copy()

    # Build sandbox namespace
    namespace = _build_namespace(df)

    # Timeout flag — set to True by the timer if execution takes too long
    timeout_occurred: list[bool] = [False]

    def _set_timeout_flag():
        timeout_occurred[0] = True

    timer = threading.Timer(_TIMEOUT_SECONDS, _set_timeout_flag)

    stdout_buffer = io.StringIO()

    try:
        timer.start()

        with contextlib.redirect_stdout(stdout_buffer):
            exec(code, namespace)  # noqa: S102

        # Check if timeout was triggered *after* exec returned
        if timeout_occurred[0]:
            elapsed_ms = (time.perf_counter() - start_time) * 1000
            return ExecutionResult(
                output_type="error",
                data=(
                    f"Error saat eksekusi kode:\n"
                    f"TimeoutError: Eksekusi melebihi batas waktu "
                    f"{_TIMEOUT_SECONDS} detik."
                ),
                stdout=stdout_buffer.getvalue(),
                error=(
                    f"TimeoutError: Eksekusi melebihi batas waktu "
                    f"{_TIMEOUT_SECONDS} detik."
                ),
                execution_time_ms=elapsed_ms,
            )

    except Exception:  # noqa: BLE001
        elapsed_ms = (time.perf_counter() - start_time) * 1000
        tb = traceback.format_exc()
        return ExecutionResult(
            output_type="error",
            data=f"Error saat eksekusi kode:\n{tb}",
            stdout=stdout_buffer.getvalue(),
            error=tb,
            execution_time_ms=elapsed_ms,
        )
    finally:
        timer.cancel()

    elapsed_ms = (time.perf_counter() - start_time) * 1000
    captured_stdout = stdout_buffer.getvalue()

    result = _detect_output(namespace, original_df, captured_stdout)

    # Patch in the real execution time
    result["execution_time_ms"] = elapsed_ms

    return result
